# Generated by Django 4.2.8 on 2023-12-21 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('vocal_path', models.CharField(max_length=255)),
                ('no_vocal_path', models.CharField(max_length=255)),
                ('bass_path', models.CharField(max_length=255)),
                ('drum_path', models.CharField(max_length=255)),
                ('other_path', models.CharField(max_length=255)),
                ('youtube_url', models.CharField(max_length=255)),
                ('audio_path', models.FileField(upload_to='audio/')),
                ('audio_key', models.CharField(max_length=20)),
                ('audio_title', models.CharField(max_length=255)),
                ('vocal_range', models.CharField(max_length=10)),
                ('bpm', models.CharField(max_length=20)),
            ],
        ),
    ]
