# Generated by Django 4.2.8 on 2023-12-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='bass_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='drum_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='music_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='no_vocal_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='other_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='vocal_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='vocal_range',
            field=models.CharField(max_length=10),
        ),
    ]
